pipeline {
    agent any
    stages {
        stage('Build Frontend') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Sembit26/TINGESO_EV1']])
                dir("appWebKarting"){
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir("appWebKarting"){
                    script {
                        withDockerRegistry(credentialsId: "docker-credentials"){
                            bat 'docker build -t sembit26/appwebkarting-frontend .'
                            bat 'docker push sembit26/appwebkarting-frontend'
                        }
                    }
                }
            }
        }
    }
}
