server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: descuento-por-cliente-frecuente
          uri: lb://descuento-por-cliente-frecuente
          predicates:
            - Path=/api/descuentoPorClienteFrecuente/**